/**
 * Maps common gene IDs to their official HGNC symbols.
 * While often the same, this provides a single source of truth and allows for aliases.
 */
export const geneticGenesMap: Record<string, string> = {
  'BRCA1': 'BRCA1',
  'BRCA2': 'BRCA2',
  'MLH1': 'MLH1',
  'MSH2': 'MSH2',
  'MSH6': 'MSH6',
  'PMS2': 'PMS2',
  'APC': 'APC',
  'TP53': 'TP53',
  'PTEN': 'PTEN',
  'STK11': 'STK11',
  'PALB2': 'PALB2',
  'CDH1': 'CDH1',
  'NF1': 'NF1',
  'ATM': 'ATM',
  'CHEK2': 'CHEK2',
  'BARD1': 'BARD1',
  'BRIP1': 'BRIP1',
  'RAD51C': 'RAD51C',
  'RAD51D': 'RAD51D',
  'EPCAM': 'EPCAM',
  'MUTYH': 'MUTYH',
  'POLE': 'POLE',
  'POLD1': 'POLD1',
  'SMAD4': 'SMAD4',
  'BMPR1A': 'BMPR1A',
  'NTHL1': 'NTHL1',
  'VHL': 'VHL',
  'FH': 'FH',
  'FLCN': 'FLCN',
  'MET': 'MET',
  'RET': 'RET',
  'MAX': 'MAX',
  'TSC1': 'TSC1',
  'TSC2': 'TSC2',
  'CDKN2A': 'CDKN2A',
  'CDK4': 'CDK4',
  'MITF': 'MITF',
  'PRSS1': 'PRSS1',
  'DICER1': 'DICER1',
  'PTCH1': 'PTCH1',
  'SUFU': 'SUFU',
  'SDHB': 'SDHB',
  'SDHC': 'SDHC',
  'SDHD': 'SDHD',
  'BAP1': 'BAP1',
  'MEN1': 'MEN1',
  'MITF_E318K': 'MITF', // Variant specific, maps to gene symbol
  'RECQL': 'RECQL',
  'GREM1': 'GREM1',
  'PALLD': 'PALLD',
  'HOXB13': 'HOXB13'
};
